const Class = require("../models/class.model");
const ClassScheduleTemplate = require("../models/classScheduleTemplate.model");
const User = require("../models/user.model");
const SlotTimetable = require("../models/slotTimetable.model");
const { calculateCombinedSchedule, getSlotsByCodes } = require("./slotTimetable.service");
const { createClassScheduleTemplate } = require("./classScheduleTemplate.service");

/**
 * Generate class name from template
 * Format: CourseCode-CourseName-Batch-Section-Group
 * Example: 21CSC204J-Design and Analysis of Algorithms-B1-A1-G1
 */
const generateClassName = (template) => {
  return `${template.courseCode}-${template.courseName}-B${template.batch}-${template.section}-G${template.group}`;
};

/**
 * Generate unique class code (6-character alphanumeric)
 */
const generateUniqueClassCode = async () => {
  const characters = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // Exclude similar characters
  let code;
  let isUnique = false;

  while (!isUnique) {
    code = "";
    for (let i = 0; i < 6; i++) {
      code += characters.charAt(Math.floor(Math.random() * characters.length));
    }

    // Check if code already exists
    const existing = await Class.findOne({ code });
    if (!existing) {
      isUnique = true;
    }
  }

  return code;
};

/**
 * Create a class from template
 * Now uses slot timetable to calculate schedule if slots are provided
 */
const createClassFromTemplate = async (template, facultyAssignment, uploadId, slotCodes = null) => {
  const {
    mainFacultyId,
    coFacultyIds = []
  } = facultyAssignment;

  // Generate unique class code
  const code = await generateUniqueClassCode();

  // Generate class name
  const name = generateClassName(template);

  // If slot codes provided, calculate schedule from slot timetable
  let scheduleData = {
    labDay: template.labDay,
    labStartTime: template.labStartTime,
    labEndTime: template.labEndTime,
    labDuration: template.labDuration
  };

  if (slotCodes && slotCodes.length > 0) {
    try {
      const combinedSchedule = await calculateCombinedSchedule(slotCodes, template.semester, template.batch);
      scheduleData = {
        labDay: combinedSchedule.day,
        labStartTime: combinedSchedule.startTime,
        labEndTime: combinedSchedule.endTime,
        labDuration: combinedSchedule.duration
      };
    } catch (error) {
      // If slot lookup fails, use template defaults
      console.warn(`Could not calculate schedule from slots: ${error.message}. Using template defaults.`);
    }
  }

  // Create class
  const classData = await Class.create({
    name,
    description: `${template.courseName} - Batch ${template.batch}, Section ${template.section}, Group ${template.group}`,
    code,
    createdBy: mainFacultyId,

    // Semester and batch/section/group info
    semester: template.semester,
    batch: template.batch,
    section: template.section,
    group: template.group,
    courseCode: template.courseCode,
    courseName: template.courseName,
    venue: template.venue,

    // Lab schedule info (from slot timetable or template)
    labSlots: template.labSlots,
    labDay: scheduleData.labDay,
    labStartTime: scheduleData.labStartTime,
    labEndTime: scheduleData.labEndTime,
    labDuration: scheduleData.labDuration,

    // Faculty assignments
    mainFaculty: mainFacultyId,
    coFaculties: coFacultyIds,

    // Tracking fields
    autoGenerated: true,
    templateId: template._id,
    uploadId: uploadId,
    isLocked: false
  });

  return classData;
};

/**
 * Create classes from teacher assignments and templates (Optimized)
 */
const createClassesFromAssignments = async (teacherAssignments, templates, uploadId, semesterId) => {
  const results = {
    created: [],
    errors: [],
    warnings: []
  };

  if (!teacherAssignments || teacherAssignments.length === 0) return results;

  try {
    console.log(`[OCR] Optimizing class creation for ${teacherAssignments.length} assignments...`);

    // 1. Group templates for fast lookup
    const templateMap = {};
    templates.forEach(t => {
      // Normalize section and courseCode to uppercase for consistent mapping
      const section = (t.section || "").toUpperCase();
      const courseCode = (t.courseCode || "").toUpperCase();
      const key = `${t.batch}-${section}-${t.group}-${courseCode}`;
      templateMap[key] = t;
    });

    // 2. Batch lookup all faculties mentioned
    const facultyNames = new Set();
    teacherAssignments.forEach(a => {
      if (a.mainFaculty) facultyNames.add(a.mainFaculty);
      if (a.coFaculty) facultyNames.add(a.coFaculty);
    });

    const faculties = await User.find({ facultyName: { $in: Array.from(facultyNames) } }).select('_id facultyName').lean();
    const facultyMap = new Map(faculties.map(f => [f.facultyName, f._id]));

    // 3. Pre-generate unique class codes
    // We generate a set of codes and check for collisions once
    const generateBatchCodes = (count) => {
      const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
      const codes = new Set();
      while (codes.size < count) {
        let code = "";
        for (let i = 0; i < 6; i++) code += chars.charAt(Math.floor(Math.random() * chars.length));
        codes.add(code);
      }
      return Array.from(codes);
    };

    let uniqueCodes = [];
    let attempts = 0;
    while (uniqueCodes.length < teacherAssignments.length && attempts < 5) {
      const candidateCodes = generateBatchCodes(teacherAssignments.length * 2);
      const existing = await Class.find({ code: { $in: candidateCodes } }).select('code').lean();
      const existingCodes = new Set(existing.map(c => c.code));

      const filtered = candidateCodes.filter(c => !existingCodes.has(c));
      uniqueCodes = [...new Set([...uniqueCodes, ...filtered])];
      attempts++;
    }

    // 4. Prepare bulk data
    const bulkOps = [];
    const processedAssignments = [];

    // Fetch existing classes for the semester to know which ones already have codes
    const existingClassesInDB = await Class.find({ semester: semesterId }).select('batch section group courseCode code').lean();
    const existingClassMap = new Map(existingClassesInDB.map(c => {
      const section = (c.section || "").toUpperCase();
      const courseCode = (c.courseCode || "").toUpperCase();
      return [`${c.batch}-${section}-${c.group}-${courseCode}`, c];
    }));
    for (let i = 0; i < teacherAssignments.length; i++) {
      const assignment = teacherAssignments[i];

      // Use pre-matched ID if available, otherwise fallback to lookup
      const mainFacultyId = assignment.mainFacultyId || facultyMap.get(assignment.mainFaculty);

      if (!mainFacultyId) {
        results.errors.push({ assignment, error: `Main faculty info missing: ${assignment.mainFaculty}` });
        continue;
      }

      // Normalize section and courseCode to match map keys
      const sectionStr = (assignment.section || "").toUpperCase();
      const courseCodeStr = (assignment.courseCode || "").toUpperCase();
      const templateKey = `${assignment.batch}-${sectionStr}-${assignment.group}-${courseCodeStr}`;
      const template = templateMap[templateKey];

      if (!template) {
        results.errors.push({ assignment, error: `No template found for ${templateKey}` });
        continue;
      }

      const existingClass = existingClassMap.get(templateKey);

      // Use pre-matched ID if available, otherwise fallback to lookup
      const coFacultyId = assignment.coFacultyId || facultyMap.get(assignment.coFaculty);
      const coFacultyIds = coFacultyId ? [coFacultyId] : [];

      if (assignment.coFaculty && !coFacultyId) {
        results.warnings.push({ assignment, warning: `Co-faculty not found: ${assignment.coFaculty}` });
      }

      const code = existingClass ? existingClass.code : uniqueCodes[bulkOps.length];
      const name = generateClassName(template);

      const classFields = {
        name,
        description: `${template.courseName} - Batch ${template.batch}, Section ${template.section}, Group ${template.group}`,
        code,
        createdBy: mainFacultyId,
        semester: template.semester,
        batch: template.batch,
        section: template.section,
        group: template.group,
        courseCode: template.courseCode,
        courseName: template.courseName,
        venue: template.venue,
        labSlots: template.labSlots,
        labDay: template.labDay,
        labStartTime: template.labStartTime,
        labEndTime: template.labEndTime,
        labDuration: template.labDuration,
        mainFaculty: mainFacultyId,
        coFaculties: coFacultyIds,
        autoGenerated: true,
        templateId: template._id,
        uploadId: uploadId,
        isLocked: false
      };

      bulkOps.push({
        updateOne: {
          filter: {
            semester: template.semester,
            batch: template.batch,
            section: template.section,
            group: template.group,
            courseCode: template.courseCode
          },
          update: { $set: classFields },
          upsert: true
        }
      });

      processedAssignments.push({ assignment, code, name });
    }

    // 5. Bulk Execute
    if (bulkOps.length > 0) {
      await Class.bulkWrite(bulkOps);

      // Re-fetch created/updated IDs for results
      const updatedClasses = await Class.find({
        semester: semesterId,
        batch: { $in: [...new Set(templates.map(t => t.batch))] }
      }).select('_id batch section group courseCode code name').lean();

      const updatedMap = new Map(updatedClasses.map(c => {
        const section = (c.section || "").toUpperCase();
        const courseCode = (c.courseCode || "").toUpperCase();
        return [`${c.batch}-${section}-${c.group}-${courseCode}`, c];
      }));

      processedAssignments.forEach((pa) => {
        const sectionStr = (pa.assignment.section || "").toUpperCase();
        const courseCodeStr = (pa.assignment.courseCode || "").toUpperCase();
        const key = `${pa.assignment.batch}-${sectionStr}-${pa.assignment.group}-${courseCodeStr}`;
        const classData = updatedMap.get(key);
        if (classData) {
          results.created.push({
            classId: classData._id,
            code: classData.code,
            name: classData.name,
            batch: classData.batch,
            section: classData.section,
            group: classData.group,
            courseCode: classData.courseCode,
            mainFaculty: pa.assignment.mainFaculty,
            coFaculty: pa.assignment.coFaculty || null
          });
        }
      });
    }

  } catch (error) {
    console.error(`[OCR] Error in createClassesFromAssignments:`, error);
    results.errors.push({ error: error.message });
  }

  return results;
};

/**
 * Validate templates exist for all assignments
 */
const validateTemplatesForAssignments = async (semesterId, teacherCombinations) => {
  const missingTemplates = [];
  const foundTemplates = [];

  for (const combo of teacherCombinations) {
    const template = await ClassScheduleTemplate.findOne({
      semester: semesterId,
      batch: combo.batch,
      section: (combo.section || "").toUpperCase(),
      group: combo.group,
      courseCode: (combo.courseCode || "").toUpperCase()
    });

    if (!template) {
      missingTemplates.push(combo); // Keep full combo for auto-creation
    } else {
      foundTemplates.push(template);
    }
  }

  return {
    valid: missingTemplates.length === 0,
    missingTemplates,
    foundTemplates,
    totalRequired: teacherCombinations.length,
    found: foundTemplates.length,
    missing: missingTemplates.length
  };
};

/**
 * Auto-create middle Templates from teacher assignments (Optimized)
 */
const autoCreateTemplatesFromAssignments = async (semesterId, missingTemplates, adminId) => {
  let createdTemplates = [];
  if (!missingTemplates || missingTemplates.length === 0) return createdTemplates;

  try {
    console.log(`[OCR] Optimizing template creation for ${missingTemplates.length} combinations...`);

    // 1. Collect all unique slot codes
    const allSlotCodes = new Set();
    missingTemplates.forEach(t => {
      (t.slotCodes || []).forEach(code => allSlotCodes.add(code.toUpperCase()));
    });

    // 2. Fetch all slots for this semester to build a robust map
    const slots = await SlotTimetable.find({ 
      semesterId: semesterId
    }).lean();
    
    // Group slots by batch and code (normalized)
    // Map key: "batch-code" where code is stripped of /X for easier matching
    const slotMap = new Map();
    slots.forEach(s => {
      const baseCode = s.slotCode.toUpperCase().replace(/\/X$/, "");
      const fullCode = s.slotCode.toUpperCase();
      
      // Store exact match
      slotMap.set(`${s.batch}-${fullCode}`, s);
      
      // Store base match as fallback if not already set (prefer exact matches)
      const baseKey = `${s.batch}-${baseCode}`;
      if (!slotMap.has(baseKey) || !slotMap.get(baseKey).slotCode.includes("/X")) {
        slotMap.set(baseKey, s);
      }
    });

    // 3. Prepare data for batch insert
    const templatesToCreate = [];

    for (const combo of missingTemplates) {
      const comboSlotCodes = (combo.slotCodes || []).map(c => c.toUpperCase());
      const comboSlots = comboSlotCodes.map(code => slotMap.get(`${combo.batch}-${code}`)).filter(Boolean);

      let labDay = null;
      let labStartTime = null;
      let labEndTime = null;
      let labDuration = 0;

      if (comboSlots.length > 0) {
        // Sort by hourOrder to ensure chronological order
        comboSlots.sort((a, b) => a.hourOrder - b.hourOrder);
        
        // Find most common day (or first day)
        const dayCounts = {};
        comboSlots.forEach(s => { dayCounts[s.day] = (dayCounts[s.day] || 0) + 1; });
        labDay = Object.keys(dayCounts).sort((a, b) => dayCounts[b] - dayCounts[a])[0];

        // START TIME: Earliest start time among all matched slots
        // END TIME: Latest end time among all matched slots
        // This handles ranges like P43,44 accurately
        labStartTime = comboSlots[0].startTime; // Earliest because of sort
        
        // Find slot with latest end time
        let latestEndTime = comboSlots[0].endTime;
        let latestMinutes = 0;
        
        comboSlots.forEach(s => {
          const [h, m] = s.endTime.split(":").map(Number);
          const currentMinutes = h * 60 + m;
          if (currentMinutes > latestMinutes) {
            latestMinutes = currentMinutes;
            latestEndTime = s.endTime;
          }
        });
        
        labEndTime = latestEndTime;

        // Calculate duration
        const [sh, sm] = labStartTime.split(":").map(Number);
        const [eh, em] = labEndTime.split(":").map(Number);
        labDuration = (eh * 60 + em) - (sh * 60 + sm);
      } else {
        console.warn(`[OCR] No DB slots found for combo ${combo.courseCode} ${combo.section} using ${comboSlotCodes.join(',')}. Creating template without lab schedule.`);
      }

      templatesToCreate.push({
        semester: semesterId,
        batch: combo.batch,
        section: combo.section.toUpperCase(),
        group: combo.group,
        courseCode: combo.courseCode.toUpperCase(),
        courseName: combo.courseName || combo.courseCode,
        venue: combo.venue || "TBD",
        labSlots: comboSlots.map(s => s._id),
        labDay,
        labStartTime,
        labEndTime,
        labDuration,
        createdBy: adminId
      });
    }

    if (templatesToCreate.length > 0) {
      try {
        await ClassScheduleTemplate.insertMany(templatesToCreate, { ordered: false });
      } catch (e) {
        // Duplicate key errors are expected when templates already exist; ignore them
        if (e.code === 11000) {
          console.warn('[OCR] Duplicate template insertion ignored');
        } else {
          throw e;
        }
      }

      const batchList = [...new Set(templatesToCreate.map(t => t.batch))];
      const sectionList = [...new Set(templatesToCreate.map(t => t.section))];
      const createdOrExisting = await ClassScheduleTemplate.find({
        semester: semesterId,
        batch: { $in: batchList },
        section: { $in: sectionList }
      }).lean();

      createdTemplates = createdOrExisting;
      console.log(`[OCR] Ensured ${createdTemplates.length} templates exist.`);
    }

  } catch (error) {
    console.error(`[OCR] Error in autoCreateTemplatesFromAssignments:`, error.message || error);
  }

  return createdTemplates;
};

/**
 * Get classes created from an upload
 */
const getClassesByUpload = async (uploadId) => {
  const classes = await Class.find({ uploadId })
    .populate("mainFaculty", "facultyName email")
    .populate("coFaculties", "facultyName email")
    .populate("semester", "name academicYear")
    .lean();

  return classes;
};

/**
 * Delete classes created from an upload (rollback)
 */
const deleteClassesByUpload = async (uploadId) => {
  const result = await Class.deleteMany({ uploadId });
  return result.deletedCount;
};

module.exports = {
  generateClassName,
  generateUniqueClassCode,
  createClassFromTemplate,
  createClassesFromAssignments,
  validateTemplatesForAssignments,
  autoCreateTemplatesFromAssignments,
  getClassesByUpload,
  deleteClassesByUpload
};