const Class = require("../models/class.model");
const ClassStudent = require("../models/classStudent.model");
const User = require("../models/user.model");

/**
 * Generate unique 6-character alphanumeric code
 */
const generateUniqueCode = async () => {
  const characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  let code;
  let isUnique = false;

  while (!isUnique) {
    code = "";
    for (let i = 0; i < 6; i++) {
      code += characters.charAt(Math.floor(Math.random() * characters.length));
    }

    // Check if code already exists
    const existing = await Class.findOne({ code });
    if (!existing) {
      isUnique = true;
    }
  }

  return code;
};

/**
 * Create a new class
 */
const createClass = async ({ name, description, teacherId }) => {
  const code = await generateUniqueCode();

  const newClass = await Class.create({
    name,
    description,
    code,
    createdBy: teacherId
  });

  return newClass;
};

/**
 * Get all classes created by a teacher
 */
const getClassesByTeacher = async (teacherId) => {
  const classes = await Class.find({ createdBy: teacherId }).sort({
    createdAt: -1
  }).lean(); // Use lean() for performance and mutability

  // Fetch student count for each class based on demographic match
  // Some classes might use ClassStudent (invite code), others use demographic matching (bulk upload)

  // 1. Get explicit enrollments for all classes to calculate unique IDs
  const classIds = classes.map(c => c._id);
  const allExplicitEnrollments = await ClassStudent.find({
    classId: { $in: classIds },
    leftAt: null
  }).select("classId studentId").lean();

  const explicitIdMap = {};
  allExplicitEnrollments.forEach(e => {
    if (!e.classId || !e.studentId) return; // Skip invalid records
    const cid = e.classId.toString();
    if (!explicitIdMap[cid]) explicitIdMap[cid] = new Set();
    explicitIdMap[cid].add(e.studentId.toString());
  });

  // 2. Add counts from bulk upload demographics (preventing duplicates)
  const populatedClasses = await Promise.all(classes.map(async (c) => {
    const classIdStr = c._id.toString();
    let uniqueStudentIds = explicitIdMap[classIdStr] || new Set();

    // If it's an auto-generated class from bulk upload, count students matching criteria
    if (c.autoGenerated && c.batch && c.section && c.group) {
      const matchingStudents = await User.find({
        role: "student",
        status: "active",
        batch: c.batch,
        section: c.section,
        group: c.group
      }).select("_id").lean();

      // Add to set to ensure uniqueness
      matchingStudents.forEach(s => {
        if (s && s._id) {
          uniqueStudentIds.add(s._id.toString());
        }
      });
    }

    return {
      ...c,
      students: new Array(uniqueStudentIds ? uniqueStudentIds.size : 0)
    };
  }));

  return populatedClasses;
};

/**
 * Get a single class by ID (with ownership verification)
 */
const getClassById = async (classId, teacherId) => {
  const classData = await Class.findOne({
    _id: classId,
    createdBy: teacherId
  });

  return classData;
};

/**
 * Update class details
 */
const updateClass = async ({ classId, name, description, teacherId }) => {
  const classData = await Class.findOneAndUpdate(
    { _id: classId, createdBy: teacherId },
    { name, description },
    { new: true }
  );

  return classData;
};

/**
 * Toggle lock status of a class
 */
const toggleClassLock = async (classId, teacherId) => {
  const classData = await Class.findOne({
    _id: classId,
    createdBy: teacherId
  });

  if (!classData) {
    return null;
  }

  classData.isLocked = !classData.isLocked;
  await classData.save();

  return classData;
};

/**
 * Delete a class
 */
const deleteClass = async (classId, teacherId) => {
  const classData = await Class.findOneAndDelete({
    _id: classId,
    createdBy: teacherId
  });

  if (!classData) {
    return null;
  }

  // Also remove all student enrollments
  await ClassStudent.deleteMany({ classId });

  return {
    message: "Class and all enrollments deleted successfully",
    deletedClassId: classId
  };
};

/**
 * Get all students in a class (active only)
 */
const getStudentsInClass = async (classId, teacherId) => {
  // Verify ownership
  const classData = await Class.findOne({
    _id: classId,
    createdBy: teacherId
  });

  if (!classData) {
    return null;
  }

  // 1. Get explicitly enrolled active students (leftAt is null)
  const explicitEnrollments = await ClassStudent.find({
    classId,
    leftAt: null
  })
    .populate("studentId", "name email registrationNumber rollNo")
    .sort({ joinedAt: -1 })
    .lean();

  let studentsList = explicitEnrollments.map((enrollment) => ({
    ...enrollment.studentId, // Spread student details
    _id: enrollment.studentId._id,
    joinedAt: enrollment.joinedAt
  }));

  // 2. If it's an auto-generated class from bulk upload, get implicitly enrolled students
  if (classData.autoGenerated && classData.batch && classData.section && classData.group) {
    const implicitlyEnrolled = await User.find({
      role: "student",
      status: "active",
      batch: classData.batch,
      section: classData.section,
      group: classData.group
    })
      .select("name email registrationNumber rollNo")
      .lean();

    // Avoid duplicates if a student is somehow in both lists (though unlikely)
    const existingIds = new Set(studentsList.map(s => s._id.toString()));

    implicitlyEnrolled.forEach(student => {
      if (!existingIds.has(student._id.toString())) {
        studentsList.push({
          ...student,
          joinedAt: classData.createdAt // Use class creation date as joined date for implicit enrollments
        });
        existingIds.add(student._id.toString());
      }
    });
  }

  // Sort students by registration number / roll number ascending
  studentsList.sort((a, b) => {
    const regA = a.registrationNumber || a.rollNo || "";
    const regB = b.registrationNumber || b.rollNo || "";
    return regA.localeCompare(regB, undefined, { numeric: true, sensitivity: 'base' });
  });

  return studentsList;
};

module.exports = {
  createClass,
  getClassesByTeacher,
  getClassById,
  updateClass,
  toggleClassLock,
  deleteClass,
  getStudentsInClass
};