const ClassStudent = require("../models/classStudent.model");
const Class = require("../models/class.model");
const User = require("../models/user.model");

/**
 * Auto-enroll a student in matching classes
 * Matches based on: batch, section, group
 */
const autoEnrollStudent = async (studentId, semesterId) => {
  // Get student details
  const student = await User.findById(studentId);

  if (!student || student.role !== "student") {
    throw new Error("Invalid student");
  }

  // Find matching classes
  const matchingClasses = await Class.find({
    semester: semesterId,
    batch: student.batch,
    section: student.section,
    group: student.group,
    autoGenerated: true
  });

  const results = {
    enrolled: [],
    skipped: [],
    errors: []
  };

  for (const classData of matchingClasses) {
    try {
      // Check if already enrolled
      const existing = await ClassStudent.findOne({
        classId: classData._id,
        studentId: studentId,
        leftAt: null
      });

      if (existing) {
        results.skipped.push({
          classId: classData._id,
          className: classData.name,
          reason: "Already enrolled"
        });
        continue;
      }

      // Enroll student
      const enrollment = await ClassStudent.create({
        classId: classData._id,
        studentId: studentId,
        autoEnrolled: true,
        joinedAt: new Date()
      });

      results.enrolled.push({
        classId: classData._id,
        className: classData.name,
        courseCode: classData.courseCode,
        courseName: classData.courseName,
        enrollmentId: enrollment._id
      });

    } catch (error) {
      results.errors.push({
        classId: classData._id,
        className: classData.name,
        error: error.message
      });
    }
  }

  return results;
};

/**
 * Auto-enroll multiple students
 */
const autoEnrollStudentsBatch = async (studentIds, semesterId) => {
  const results = {
    totalStudents: studentIds.length,
    studentsEnrolled: 0,
    totalEnrollments: 0,
    errors: []
  };

  try {
    // 1. Fetch all students in one go
    const students = await User.find({ _id: { $in: studentIds }, role: "student" });
    if (students.length === 0) return results;

    // 2. Identify unique batch/section/group combinations
    const criteria = new Set();
    students.forEach(s => {
      criteria.add(`${s.batch}-${s.section}-${s.group}`);
    });

    // 3. Fetch all matching classes for the semester matching those criteria
    // We fetch all auto-generated classes for the semester and filter in memory
    const allClasses = await Class.find({
      semester: semesterId,
      autoGenerated: true
    });

    const classLookup = {}; // Key: "batch-section-group", Value: [Classes]
    allClasses.forEach(c => {
      const key = `${c.batch}-${c.section}-${c.group}`;
      if (!classLookup[key]) classLookup[key] = [];
      classLookup[key].push(c);
    });

    // 4. Fetch all existing enrollments for these students in these classes
    const classIds = allClasses.map(c => c._id);
    const existingEnrollments = await ClassStudent.find({
      studentId: { $in: studentIds },
      classId: { $in: classIds },
      leftAt: null
    });

    const enrollmentSet = new Set();
    existingEnrollments.forEach(e => {
      enrollmentSet.add(`${e.studentId}-${e.classId}`);
    });

    // 5. Prepare bulk operations
    const newEnrollments = [];
    const studentImpacted = new Set();

    students.forEach(student => {
      const key = `${student.batch}-${student.section}-${student.group}`;
      const matchingClasses = classLookup[key] || [];

      matchingClasses.forEach(classData => {
        if (!enrollmentSet.has(`${student._id}-${classData._id}`)) {
          newEnrollments.push({
            classId: classData._id,
            studentId: student._id,
            autoEnrolled: true,
            joinedAt: new Date()
          });
          studentImpacted.add(student._id.toString());
        }
      });
    });

    // 6. Bulk Insert
    if (newEnrollments.length > 0) {
      await ClassStudent.insertMany(newEnrollments, { ordered: false });
      results.studentsEnrolled = studentImpacted.size;
      results.totalEnrollments = newEnrollments.length;
    }

  } catch (error) {
    console.error("[AUTO-ENROLL] Bulk error:", error);
    results.errors.push({ error: error.message });
  }

  return results;
};

/**
 * Auto-enroll all students from an upload
 */
const autoEnrollStudentsFromUpload = async (uploadId, semesterId) => {
  // Find all students created by this upload
  const students = await User.find({
    role: "student",
    createdBy: uploadId,
    createdByModel: "Upload"
  });

  const studentIds = students.map(s => s._id);

  return await autoEnrollStudentsBatch(studentIds, semesterId);
};

/**
 * Get enrollment statistics for an upload
 */
const getEnrollmentStatsByUpload = async (uploadId) => {
  // Get all students from upload
  const students = await User.find({
    role: "student",
    createdBy: uploadId,
    createdByModel: "Upload"
  });

  // Get their enrollments
  const enrollments = await ClassStudent.find({
    studentId: { $in: students.map(s => s._id) },
    autoEnrolled: true
  }).populate("classId", "name courseCode batch section group");

  // Calculate stats
  const stats = {
    totalStudents: students.length,
    totalEnrollments: enrollments.length,
    averageClassesPerStudent: (enrollments.length / students.length).toFixed(2),
    byBatch: {},
    bySection: {},
    byGroup: {}
  };

  students.forEach(student => {
    const studentEnrollments = enrollments.filter(
      e => e.studentId.toString() === student._id.toString()
    );

    // By batch
    if (!stats.byBatch[student.batch]) {
      stats.byBatch[student.batch] = { students: 0, enrollments: 0 };
    }
    stats.byBatch[student.batch].students++;
    stats.byBatch[student.batch].enrollments += studentEnrollments.length;

    // By section
    if (!stats.bySection[student.section]) {
      stats.bySection[student.section] = { students: 0, enrollments: 0 };
    }
    stats.bySection[student.section].students++;
    stats.bySection[student.section].enrollments += studentEnrollments.length;

    // By group
    if (!stats.byGroup[student.group]) {
      stats.byGroup[student.group] = { students: 0, enrollments: 0 };
    }
    stats.byGroup[student.group].students++;
    stats.byGroup[student.group].enrollments += studentEnrollments.length;
  });

  return stats;
};

/**
 * Validate enrollment: Check if classes exist for student's batch-section-group
 */
const validateEnrollmentPossible = async (semesterId, batch, section, group) => {
  const matchingClasses = await Class.find({
    semester: semesterId,
    batch,
    section,
    group,
    autoGenerated: true
  });

  return {
    possible: matchingClasses.length > 0,
    classCount: matchingClasses.length,
    classes: matchingClasses.map(c => ({
      name: c.name,
      courseCode: c.courseCode,
      courseName: c.courseName
    }))
  };
};

/**
 * Delete auto-enrollments from an upload (rollback)
 */
const deleteEnrollmentsByUpload = async (uploadId) => {
  // Find all students from upload
  const students = await User.find({
    role: "student",
    createdBy: uploadId,
    createdByModel: "Upload"
  });

  // Delete their auto-enrollments
  const result = await ClassStudent.deleteMany({
    studentId: { $in: students.map(s => s._id) },
    autoEnrolled: true
  });

  return result.deletedCount;
};

/**
 * Get student's enrolled classes with schedule details
 */
const getStudentEnrolledClasses = async (studentId) => {
  const enrollments = await ClassStudent.find({
    studentId,
    leftAt: null
  })
    .populate({
      path: "classId",
      populate: [
        { path: "mainFaculty", select: "facultyName email" },
        { path: "coFaculties", select: "facultyName email" },
        { path: "semester", select: "name academicYear" }
      ]
    })
    .lean();

  return enrollments.map(enrollment => ({
    enrollmentId: enrollment._id,
    classId: enrollment.classId._id,
    className: enrollment.classId.name,
    code: enrollment.classId.code,
    courseCode: enrollment.classId.courseCode,
    courseName: enrollment.classId.courseName,
    batch: enrollment.classId.batch,
    section: enrollment.classId.section,
    group: enrollment.classId.group,
    venue: enrollment.classId.venue,
    labDay: enrollment.classId.labDay,
    labStartTime: enrollment.classId.labStartTime,
    labEndTime: enrollment.classId.labEndTime,
    labDuration: enrollment.classId.labDuration,
    mainFaculty: enrollment.classId.mainFaculty,
    coFaculties: enrollment.classId.coFaculties,
    semester: enrollment.classId.semester,
    autoEnrolled: enrollment.autoEnrolled,
    joinedAt: enrollment.joinedAt
  }));
};

module.exports = {
  autoEnrollStudent,
  autoEnrollStudentsBatch,
  autoEnrollStudentsFromUpload,
  getEnrollmentStatsByUpload,
  validateEnrollmentPossible,
  deleteEnrollmentsByUpload,
  getStudentEnrolledClasses
};