const Class = require("../models/class.model");
const ClassStudent = require("../models/classStudent.model");

/**
 * Get teacher's weekly schedule
 * Returns all classes where teacher is main faculty or co-faculty
 */
const getTeacherWeeklySchedule = async (teacherId) => {
  // Find all classes where teacher is main faculty or co-faculty
  const classes = await Class.find({
    $or: [
      { mainFaculty: teacherId },
      { coFaculties: teacherId }
    ]
  })
    .populate("semester", "name academicYear")
    .populate("mainFaculty", "facultyName email")
    .populate("coFaculties", "facultyName email")
    .lean();

  // Group by day
  const schedule = {
    Monday: [],
    Tuesday: [],
    Wednesday: [],
    Thursday: [],
    Friday: [],
    Saturday: []
  };

  // Get student count for each class
  for (const classData of classes) {
    const studentCount = await ClassStudent.countDocuments({
      classId: classData._id,
      leftAt: null
    });

    const entry = {
      classId: classData._id,
      className: classData.name,
      code: classData.code,
      courseCode: classData.courseCode,
      courseName: classData.courseName,
      venue: classData.venue,
      labDay: classData.labDay,
      labStartTime: classData.labStartTime,
      labEndTime: classData.labEndTime,
      labDuration: classData.labDuration,
      batch: classData.batch,
      section: classData.section,
      group: classData.group,
      semester: classData.semester?.name || null,
      isMainFaculty: classData.mainFaculty && teacherId ? classData.mainFaculty._id?.toString() === teacherId.toString() : false,
      mainFaculty: classData.mainFaculty?.facultyName || "TBA",
      coFaculties: Array.isArray(classData.coFaculties) ? classData.coFaculties.map(cf => cf?.facultyName).filter(Boolean) : [],
      studentCount,
      autoGenerated: classData.autoGenerated
    };

    if (classData.labDay && schedule[classData.labDay]) {
      schedule[classData.labDay].push(entry);
    }
  }

  // Sort each day by start time
  Object.keys(schedule).forEach(day => {
    schedule[day].sort((a, b) => {
      if (!a.labStartTime) return 1;
      if (!b.labStartTime) return -1;
      return a.labStartTime.localeCompare(b.labStartTime);
    });
  });

  return {
    schedule,
    totalClasses: classes.length,
    daysWithClasses: Object.keys(schedule).filter(day => schedule[day].length > 0)
  };
};

/**
 * Get teacher's daily schedule for a specific day
 */
const getTeacherDailySchedule = async (teacherId, day) => {
  // Validate day
  const validDays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
  if (!validDays.includes(day)) {
    throw new Error(`Invalid day. Must be one of: ${validDays.join(", ")}`);
  }

  // Find all classes for this day
  const classes = await Class.find({
    $or: [
      { mainFaculty: teacherId },
      { coFaculties: teacherId }
    ],
    labDay: day
  })
    .populate("semester", "name academicYear")
    .populate("mainFaculty", "facultyName email mobile")
    .populate("coFaculties", "facultyName email")
    .lean();

  // Get student count and details for each class
  const schedulePromises = classes.map(async (classData) => {
    const studentCount = await ClassStudent.countDocuments({
      classId: classData._id,
      leftAt: null
    });

    return {
      classId: classData._id,
      className: classData.name,
      code: classData.code,
      courseCode: classData.courseCode,
      courseName: classData.courseName,
      venue: classData.venue,
      labStartTime: classData.labStartTime,
      labEndTime: classData.labEndTime,
      labDuration: classData.labDuration,
      batch: classData.batch,
      section: classData.section,
      group: classData.group,
      semester: classData.semester?.name || null,
      isMainFaculty: classData.mainFaculty && teacherId ? classData.mainFaculty._id?.toString() === teacherId.toString() : false,
      mainFaculty: {
        name: classData.mainFaculty?.facultyName || "TBA",
        email: classData.mainFaculty?.email || null,
        mobile: classData.mainFaculty?.mobile || null
      },
      coFaculties: Array.isArray(classData.coFaculties) ? classData.coFaculties.filter(cf => cf).map(cf => ({
        name: cf?.facultyName || "TBA",
        email: cf?.email || null
      })) : [],
      studentCount
    };
  });

  const scheduleData = await Promise.all(schedulePromises);

  // Sort by start time
  scheduleData.sort((a, b) => {
    if (!a.labStartTime) return 1;
    if (!b.labStartTime) return -1;
    return a.labStartTime.localeCompare(b.labStartTime);
  });

  return {
    day,
    schedule: scheduleData,
    totalClasses: scheduleData.length
  };
};

/**
 * Get upcoming classes (next 7 days)
 */
const getUpcomingClasses = async (teacherId) => {
  const daysOfWeek = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
  const today = new Date();

  // Get all teacher's classes
  const classes = await Class.find({
    $or: [
      { mainFaculty: teacherId },
      { coFaculties: teacherId }
    ]
  })
    .populate("semester", "name academicYear")
    .populate("mainFaculty", "facultyName")
    .lean();

  // Build upcoming schedule
  const upcoming = [];

  for (let i = 0; i < 7; i++) {
    const futureDate = new Date(today);
    futureDate.setDate(today.getDate() + i);
    const dayName = daysOfWeek[futureDate.getDay()];

    // Get student count for each class on this day
    const classesOnDayPromises = classes
      .filter(cls => cls.labDay === dayName)
      .map(async (classData) => {
        const studentCount = await ClassStudent.countDocuments({
          classId: classData._id,
          leftAt: null
        });

        return {
          date: futureDate.toISOString().split('T')[0],
          dayName,
          classId: classData._id,
          className: classData.name,
          code: classData.code,
          courseCode: classData.courseCode,
          courseName: classData.courseName,
          venue: classData.venue,
          labStartTime: classData.labStartTime,
          labEndTime: classData.labEndTime,
          batch: classData.batch,
          section: classData.section,
          group: classData.group,
          isMainFaculty: classData.mainFaculty && teacherId ? classData.mainFaculty._id?.toString() === teacherId.toString() : false,
          semester: classData.semester?.name || null,
          studentCount
        };
      });

    const classesOnDay = await Promise.all(classesOnDayPromises);
    
    // Sort by time
    classesOnDay.sort((a, b) => a.labStartTime.localeCompare(b.labStartTime));

    if (classesOnDay.length > 0) {
      upcoming.push(...classesOnDay);
    }
  }

  return {
    upcoming,
    totalUpcoming: upcoming.length,
    startDate: today.toISOString().split('T')[0],
    endDate: new Date(today.getTime() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]
  };
};

/**
 * Get all teacher's classes (simple list)
 */
const getTeacherAllClasses = async (teacherId) => {
  const classes = await Class.find({
    $or: [
      { mainFaculty: teacherId },
      { coFaculties: teacherId }
    ]
  })
    .populate("semester", "name academicYear")
    .populate("mainFaculty", "facultyName email")
    .populate("coFaculties", "facultyName email")
    .lean();

  // Get student count for each class
  const classesWithCountPromises = classes.map(async (classData) => {
    const studentCount = await ClassStudent.countDocuments({
      classId: classData._id,
      leftAt: null
    });

    return {
      classId: classData._id,
      className: classData.name,
      code: classData.code,
      courseCode: classData.courseCode,
      courseName: classData.courseName,
      venue: classData.venue,
      labDay: classData.labDay,
      labStartTime: classData.labStartTime,
      labEndTime: classData.labEndTime,
      batch: classData.batch,
      section: classData.section,
      group: classData.group,
      semester: classData.semester?.name || null,
      isMainFaculty: classData.mainFaculty && teacherId ? classData.mainFaculty._id?.toString() === teacherId.toString() : false,
      mainFaculty: classData.mainFaculty?.facultyName || "TBA",
      coFaculties: Array.isArray(classData.coFaculties) ? classData.coFaculties.map(cf => cf?.facultyName).filter(Boolean) : [],
      studentCount,
      autoGenerated: classData.autoGenerated,
      createdAt: classData.createdAt
    };
  });

  const classesWithCount = await Promise.all(classesWithCountPromises);

  return {
    classes: classesWithCount,
    total: classesWithCount.length
  };
};

/**
 * Get teacher's teaching load summary
 */
const getTeacherLoadSummary = async (teacherId) => {
  const classes = await Class.find({
    $or: [
      { mainFaculty: teacherId },
      { coFaculties: teacherId }
    ]
  }).lean();

  const asMainFaculty = classes.filter(
    cls => cls.mainFaculty?.toString() === teacherId.toString()
  ).length;

  const asCoFaculty = classes.filter(
    cls => cls.coFaculties?.some(cf => cf.toString() === teacherId.toString())
  ).length;

  // Calculate total weekly hours
  let totalMinutes = 0;
  classes.forEach(cls => {
    totalMinutes += cls.labDuration || 0;
  });

  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;

  // Get unique batches and sections
  const uniqueBatches = [...new Set(classes.map(cls => cls.batch))];
  const uniqueSections = [...new Set(classes.map(cls => cls.section))];

  return {
    totalClasses: classes.length,
    asMainFaculty,
    asCoFaculty,
    weeklyHours: {
      total: totalMinutes,
      hours,
      minutes,
      formatted: `${hours}h ${minutes}m`
    },
    uniqueBatches: uniqueBatches.length,
    uniqueSections: uniqueSections.length,
    batches: uniqueBatches.sort(),
    sections: uniqueSections.sort()
  };
};

module.exports = {
  getTeacherWeeklySchedule,
  getTeacherDailySchedule,
  getUpcomingClasses,
  getTeacherAllClasses,
  getTeacherLoadSummary
};