const mongoose = require("mongoose");

const classSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
      trim: true
    },
    description: {
      type: String,
      trim: true,
      default: ""
    },
    code: {
      type: String,
      required: true,
      unique: true, // ✅ Creates index automatically - no need for schema.index()
      uppercase: true,
      length: 6
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true
    },
    isLocked: {
      type: Boolean,
      default: false
    },

    // 🔥 NEW: Semester and batch/section/group fields
    semester: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Semester",
      default: null
      // Links to semester (for auto-generated classes)
    },

    batch: {
      type: Number,
      default: null,
      enum: [1, 2]
      // Batch 1 or Batch 2 (for auto-generated classes)
    },

    section: {
      type: String,
      trim: true,
      uppercase: true,
      default: null
      // Examples: "A1", "A2", "B1" (for auto-generated classes)
    },

    group: {
      type: Number,
      default: null,
      enum: [1, 2]
      // Group 1 or Group 2 (for auto-generated classes)
    },

    courseCode: {
      type: String,
      trim: true,
      uppercase: true,
      default: null
      // Example: "21CSC204J" (for auto-generated classes)
    },

    courseName: {
      type: String,
      trim: true,
      default: null
      // Example: "Design and Analysis of Algorithms"
    },

    venue: {
      type: String,
      trim: true,
      default: null
      // Example: "TP008", "TP016"
    },

    // 🔥 NEW: Lab schedule fields
    labSlots: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "LabSlot"
      }
    ],

    labDay: {
      type: String,
      enum: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
      default: null
      // Day of the week when lab occurs
    },

    labStartTime: {
      type: String,
      default: null
      // Format: "HH:MM" - Start time of lab
    },

    labEndTime: {
      type: String,
      default: null
      // Format: "HH:MM" - End time of lab
    },

    labDuration: {
      type: Number,
      default: null
      // Total lab duration in minutes
    },

    // 🔥 NEW: Faculty assignment fields
    mainFaculty: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null
      // Main faculty teaching this class
    },

    coFaculties: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User"
      }
      // Co-faculties (can be empty array)
    ],

    // 🔥 NEW: Auto-generation tracking fields
    autoGenerated: {
      type: Boolean,
      default: false
      // True if class was auto-created from upload
    },

    templateId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "ClassScheduleTemplate",
      default: null
      // Reference to the template used to create this class
    },

    uploadId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Upload",
      default: null
      // Reference to the upload that created this class
    }
  },
  {
    timestamps: true
  }
);

// ✅ FIXED: Removed duplicate code index
// Index for faster code lookup
// classSchema.index({ code: 1 }); // ❌ REMOVED - already created by unique: true

// ✅ Keep this index (no duplicate)
// Index for teacher's classes
classSchema.index({ createdBy: 1 });

// 🔥 NEW: Indexes for semester and batch/section/group
classSchema.index({ semester: 1 });
classSchema.index({ semester: 1, batch: 1, section: 1, group: 1 });
classSchema.index({ courseCode: 1 });
classSchema.index({ autoGenerated: 1 });
classSchema.index({ uploadId: 1 });

// 🔥 NEW: Index for faculty assignments
classSchema.index({ mainFaculty: 1 });
classSchema.index({ coFaculties: 1 });

module.exports = mongoose.model("Class", classSchema);